# Generated by Django 5.2.8 on 2026-03-21 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliverymanager", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="delivery",
            name="updatedAt",
        ),
        migrations.AlterField(
            model_name="delivery",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="latitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="longitude",
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_time", models.FloatField()),
                ("total_distance", models.FloatField()),
                ("deliveries", models.ManyToManyField(to="deliverymanager.delivery")),
            ],
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "route",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="deliverymanager.route",
                    ),
                ),
            ],
        ),
    ]
