# Generated by Django 5.2.8 on 2026-03-21 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "deliverymanager",
            "0002_remove_delivery_updatedat_alter_delivery_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomDelivery",
            fields=[
                (
                    "delivery_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="deliverymanager.delivery",
                    ),
                ),
                ("priority_level", models.IntegerField()),
                ("scheduled_time", models.DateTimeField()),
            ],
            bases=("deliverymanager.delivery",),
        ),
    ]
