# Generated by Django 5.2.8 on 2026-03-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliverymanager", "0003_customdelivery"),
    ]

    operations = [
        migrations.RenameField(
            model_name="delivery",
            old_name="createdAt",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="route",
            name="deliveries",
            field=models.ManyToManyField(
                blank=True, related_name="routes", to="deliverymanager.delivery"
            ),
        ),
    ]
