# Generated by Django 5.2.8 on 2026-03-21 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliverymanager", "0004_rename_createdat_delivery_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="route",
            name="deliveries",
        ),
        migrations.AddField(
            model_name="delivery",
            name="route",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deliveries",
                to="deliverymanager.route",
            ),
        ),
    ]
