# Generated by Django 5.2.8 on 2026-03-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliverymanager", "0005_remove_route_deliveries_delivery_route"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="route_order",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
