# Generated by Django 5.2.8 on 2026-03-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliverymanager", "0006_delivery_route_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="leg_distance_meters",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="delivery",
            name="leg_duration_seconds",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
