# Generated by Django 5.2.8 on 2026-03-22 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliverymanager", "0007_delivery_leg_distance_meters_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("unassigned", "Unassigned"),
                    ("assigned", "Assigned"),
                    ("delivered", "Delivered"),
                ],
                default="unassigned",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deliveries",
                to="deliverymanager.route",
            ),
        ),
    ]
