# Generated by Django 5.2.8 on 2026-03-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliverymanager", "0008_delivery_status_alter_delivery_route"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="is_custom",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("Unassigned", "Unassigned"),
                    ("Assigned", "Assigned"),
                    ("Delivered", "Delivered"),
                ],
                default="Unassigned",
                max_length=20,
            ),
        ),
    ]
