# Generated by Django 5.2.8 on 2026-03-29 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliverymanager", "0009_delivery_is_custom_alter_delivery_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="route",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="driver",
                to="deliverymanager.route",
            ),
        ),
    ]
